### ISSUE TITLE
broken after 15 august comfyui updated

### ISSUE THREAD

**Issue by ammahmoudi** [ty0x2333/ComfyUI-Dev-Utils#17]
Hi. after updated comfy ui in 15 august the pluign wont load:
Traceback (most recent call last):
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Dev-Utils\__init__.py", line 3, in <module>
    from .nodes.execution_time import ExecutionTime
  File "C:\Users\Public\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Dev-Utils\nodes\execution_time.py", line 24, in <module>
    origin_recursive_execute = execution.recursive_execute
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'execution' has no attribute 'recursive_execute'

Cannot import C:\Users\Public\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Dev-Utils module for custom nodes: module 'execution' has no attribute 'recursive_execute'

**Comment by 807502278** [comment]
#15 The author has fixed it

**Comment by ty0x2333** [comment]
@ammahmoudi 

Please upgrade ComfyUI-Dev-Utils to the latest version.

same #15
